### ISSUE TITLE
Join forces?

### ISSUE THREAD

**Issue by hype3** [wizbright/waybox#26]
Why don't you guys join forces with [labwc](https://github.com/johanmalm/labwc) or maybe your goals are different than this openbox project?

**Comment by jubalh** [comment]
First commit of waybox: Feb 19, 2018
First commit of labwc: May 11, 2019

Why do you ask this question here then?

**Comment by keithbowes** [comment]
> 
> Why do you ask this question here then?

Well, labwc does seem to be further along, but we have the better name :)

Though, there's nothing wrong with having competing compositors, just like there are seemingly endless *box X window managers.

**Comment by boydkelly** [comment]
I think waybox is the right name.   In any case it would be awesome to see the project(s) come along...

**Comment by emanuelserpa** [comment]
Yeah, maybe libwc and waybox should join forces indeed.
