### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by m-kru** [wizbright/waybox#27]
What is the current status of the project? Do you have any list of features that have not yet been ported?

**Comment by hcsubser** [comment]
I would love to know that aswell seens to not have been updated since may

**Comment by hulloanson** [comment]
2021. asking the same question

**Comment by datamaskinen** [comment]
....

**Comment by keithbowes** [comment]
I have a list of things I want to do on my computer.  Maybe I should put them in a TODO file or create milestone trackers.  Do however see issue #1 .

**Comment by wizbright** [comment]
I plan to actually try to work on this since I have more time now actually. I'm sorry i've been gone for so long @keithbowes

**Comment by keithbowes** [comment]
Oh, by the way.  The builds failing isn't my fault.  It seems that GitHub can't correctly get wlroots to compile (it used to be missing EGL, now it's missing DRM).
