### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by AnonymousDebug** [wizbright/waybox#29]
Steps to reproduce:
1.`git clone https://github.com/wizbright/waybox.git`
2. `sudo pacman -S meson wlroots wayland xkbcommon`
3. `meson build`
4. `cd build`
5. `ninja`

Error: 
`[1/2] Compiling C object waybox/waybox.p/server.c.o
FAILED: waybox/waybox.p/server.c.o 
cc -Iwaybox/waybox.p -Iwaybox -I../waybox -I../include -I/usr/include/libdrm -I/usr/include/pixman-1 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -g -Wno-unused-parameter -DWLR_USE_UNSTABLE '-DPACKAGE_NAME="Waybox"' '-DPACKAGE_VERSION="0.1.0"' '-DGETTEXT_PACKAGE="waybox"' '-DLOCALEDIR="/usr/local/share/locale"' -MD -MQ waybox/waybox.p/server.c.o -MF waybox/waybox.p/server.c.o.d -o waybox/waybox.p/server.c.o -c ../waybox/server.c
../waybox/server.c: In function ‘wb_create_backend’:
../waybox/server.c:18:28: error: implicit declaration of function ‘wlr_backend_get_renderer’; did you mean ‘wlr_backend_get_session’? [-Werror=implicit-function-declaration]
   18 |         server->renderer = wlr_backend_get_renderer(server->backend);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~
      |                            wlr_backend_get_session
../waybox/server.c:18:26: error: assignment to ‘struct wlr_renderer *’ from ‘int’ makes pointer from integer without a cast [-Werror=int-conversion]
   18 |         server->renderer = wlr_backend_get_renderer(server->backend);
      |                          ^
cc1: all warnings being treated as errors
ninja: build stopped: subcommand failed.`

Information: 
System: Arch Linux
Kernel: 5.15.17-1-lts
CPU: CPU: Intel i3-2348M (4) @ 2.300GHz
GPU: GPU: Intel 2nd Generation Core Process
Log file at build/meson-logs/meson-log.txt- [meson-log.txt](https://github.com/wizbright/waybox/files/7972400/meson-log.txt)

Current Local Clone: [current_local_clone.tar.gz](https://github.com/wizbright/waybox/files/7972427/current_local_clone.tar.gz)

**Comment by keithbowes** [comment]
This should be fixed.  If you're still having problems with the latest master code, you can reopen this issue.
