### ISSUE TITLE
Can't build against WLRoots 0.16.2

### ISSUE THREAD

**Issue by vanfanel** [wizbright/waybox#35]
Hi there,

Trying to build against WLRoots 0.16.2, I see this:
```

../waybox/xdg_shell.c: In function ‘focus_view’:
../waybox/xdg_shell.c:76:4: error: ‘previous’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   76 |    wlr_xdg_toplevel_set_activated(previous->toplevel, false);
```

Is this a known problem?

**Comment by keithbowes** [comment]
Thanks.  No, it wasn't known.  I didn't realize that such innocuous code that compiles fine with GCC would cause an error with Clang.  I did update the build manifests to build with both GCC and Clang to hopefully avoid this situation in the future.
